# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testfft <- function(x) {
    invisible(.Call(`_orderedPvalue_testfft`, x))
}

test <- function() {
    invisible(.Call(`_orderedPvalue_test`))
}

testConv <- function(x, y) {
    invisible(.Call(`_orderedPvalue_testConv`, x, y))
}

compute_prob <- function(m, R_g_value, R_h_value, n_t, R_diff_t) {
    .Call(`_orderedPvalue_compute_prob`, m, R_g_value, R_h_value, n_t, R_diff_t)
}

compute_prob_fft <- function(m, R_g_value, R_h_value, n_t, R_diff_t) {
    .Call(`_orderedPvalue_compute_prob_fft`, m, R_g_value, R_h_value, n_t, R_diff_t)
}

