# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function() {
    .Call(`_orderedPvalue_test`)
}

test <- function(x_real, x_img, y_real, y_img) {
    invisible(.Call(`_orderedPvalue_test`, x_real, x_img, y_real, y_img))
}

testfft <- function(x_real) {
    .Call(`_orderedPvalue_testfft`, x_real)
}

main1 <- function(N) {
    .Call(`_orderedPvalue_main1`, N)
}

compute_prob <- function(m, R_g_value, R_h_value, n_t, R_diff_t) {
    .Call(`_orderedPvalue_compute_prob`, m, R_g_value, R_h_value, n_t, R_diff_t)
}

compute_prob_fft <- function(m, R_g_value, R_h_value, n_t, R_diff_t) {
    .Call(`_orderedPvalue_compute_prob_fft`, m, R_g_value, R_h_value, n_t, R_diff_t)
}

